spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/telemetry_analyzer
    username: postgres
    password: shareit
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  kafka:
    common:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    consumers:
      hubs:
        bootstrap-servers: localhost:9092
        group-id: telemetry-analyzer-hubs
        client-id: telemetry.analyzer.hubs
        value-deserializer: ru.practicum.kafka.deserializer.HubEventDeserializer
        topics:
          - telemetry.hubs.v1
        concurrency: 3   # кол-во потоков (консюмеров) в группе
      snapshots:
        bootstrap-servers: localhost:9092
        group-id: telemetry-analyzer-snapshots
        client-id: telemetry.analyzer.snapshots
        value-deserializer: ru.practicum.kafka.deserializer.SensorsSnapshotDeserializer
        topics:
          - telemetry.snapshots.v1
        concurrency: 2

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext



